# Generated by Django 4.1.3 on 2022-12-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tptest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('specialty', models.TextField()),
                ('insurance', models.TextField()),
                ('distance', models.TextField()),
            ],
        ),
    ]
