# Generated by Django 4.1.3 on 2022-12-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armss', '0002_tptest2_alter_tptest_distance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tptest2',
            new_name='Tptestnew',
        ),
    ]
