# Generated by Django 3.1 on 2022-12-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userentry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='insurance',
        ),
        migrations.AddField(
            model_name='user',
            name='insuranceaccepted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='insurancedetails',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='available_times1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='available_times2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='available_times3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='available_times4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='available_times5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='distance',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialty',
            field=models.TextField(blank=True, default=''),
        ),
    ]
