# Generated by Django 3.1 on 2022-12-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userentry', '0002_auto_20221204_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='endtime',
            field=models.CharField(choices=[('9', '9'), ('9:30', '9:30'), ('10', '10'), ('10:30', '10:30'), ('11', '11'), ('11:30', '11:30'), ('12', '12'), ('12:30', '12:30'), ('13', '13'), ('13:30', '13:30'), ('14', '14')], default='9', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='starttime',
            field=models.CharField(choices=[('9', '9'), ('9:30', '9:30'), ('10', '10'), ('10:30', '10:30'), ('11', '11'), ('11:30', '11:30'), ('12', '12'), ('12:30', '12:30'), ('13', '13'), ('13:30', '13:30'), ('14', '14')], default='9', max_length=5),
        ),
    ]
