# Generated by Django 3.1 on 2022-12-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userentry', '0004_auto_20221204_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.TextField(default=0),
        ),
    ]
