# Generated by Django 3.1 on 2022-12-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userentry', '0006_auto_20221204_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
