# Generated by Django 3.1 on 2022-12-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userentry', '0008_auto_20221204_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='insuranceaccepted',
            field=models.CharField(choices=[('OIC', 'OIC'), ('oman', 'Oman'), ('xyz', 'yxz')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='insurancedetails',
            field=models.CharField(choices=[('OIC', 'OIC'), ('oman', 'Oman'), ('xyz', 'yxz')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialty',
            field=models.CharField(choices=[('GP', 'GP'), ('Dentist', 'Dentist'), ('opt', 'Ophthalmologist'), ('ent', 'ENT')], default='', max_length=100),
        ),
    ]
