# Generated by Django 3.1 on 2022-12-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userentry', '0010_auto_20221204_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='starttime',
            field=models.CharField(choices=[('9:00', '9:00'), ('9:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00')], default='9', max_length=5),
        ),
    ]
