# Generated by Django 3.1 on 2022-12-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userentry', '0013_auto_20221204_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='insuranceaccepted',
            field=models.CharField(blank=True, choices=[('OIC', 'OIC'), ('Geoblue', 'Geoblue'), ('ADNIC', 'ADNIC')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='insurancedetails',
            field=models.CharField(blank=True, choices=[('OIC', 'OIC'), ('Geoblue', 'Geoblue'), ('ADNIC', 'ADNIC')], default='', max_length=100),
        ),
    ]
