# Generated by Django 4.1.3 on 2022-12-04 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userentry', '0010_alter_user_endtime_alter_user_insuranceaccepted_and_more'),
        ('userentry', '0013_auto_20221204_2117'),
    ]

    operations = [
    ]
