# Generated by Django 4.1.3 on 2022-12-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userentry', '0014_merge_20221204_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='endtime',
            field=models.CharField(blank=True, choices=[('9:00', '9:00'), ('9:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='insuranceaccepted',
            field=models.CharField(blank=True, choices=[('OIC', 'OIC'), ('GEOBLUE', 'GEOBLUE'), ('ADNIC', 'ADNIC')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='insurancedetails',
            field=models.CharField(blank=True, choices=[('OIC', 'OIC'), ('GEOBLUE', 'GEOBLUE'), ('ADNIC', 'ADNIC')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='starttime',
            field=models.CharField(blank=True, choices=[('9:00', '9:00'), ('9:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00')], default='', max_length=5),
        ),
    ]
