# Generated by Django 3.1 on 2022-12-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userentry', '0014_auto_20221204_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=1000, unique=True),
        ),
    ]
