# Generated by Django 3.1 on 2022-12-05 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userentry', '0015_auto_20221205_0805'),
        ('userentry', '0015_alter_user_endtime_alter_user_insuranceaccepted_and_more'),
    ]

    operations = [
    ]
