# Generated by Django 4.1.3 on 2022-12-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userentry', '0015_alter_user_endtime_alter_user_insuranceaccepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=1000, unique=True),
        ),
    ]
