# Generated by Django 3.1 on 2022-12-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userentry', '0016_merge_20221205_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=1000, unique=True),
        ),
    ]
