# Generated by Django 4.1.3 on 2022-12-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
