# Generated by Django 4.1.3 on 2022-12-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creds', '0002_credential_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='user',
        ),
    ]
